System.Reflection.AmbiguousMatchException: 发现不明确的匹配。
   在 System.Windows.Forms.Control.MarshaledInvoke(Control caller, Delegate method, Object[] args, Boolean synchronous)
   在 System.Windows.Forms.Control.Invoke(Delegate method, Object[] args)
   在 ns3.Class14.ns0.Class144.Resolve(IAssemblyReference iassemblyReference_0, String string_0)
   在 ns3.Class228.ns0.Class143.Resolve(IAssemblyReference iassemblyReference_0, String string_0)
   在 ns18.Class255.Load(IAssemblyReference iassemblyReference_0, String string_0)
   在 Reflector.CodeModel.Memory.AssemblyReference.Resolve()
   在 ns18.Class74.smethod_4(ITypeReference itypeReference_0)
   在 ns18.Class272.Resolve()
   在 ns25.Class595.ns0.Class658.vmethod_111(ILiteralExpression iliteralExpression_0)
   在 ns64.Class592.vmethod_55(IExpression iexpression_0)
   在 ns25.Class595.ns0.Class658.method_30(IExpression iexpression_0, IType itype_2)
   在 ns25.Class595.ns0.Class658.vmethod_97(IObjectCreateExpression iobjectCreateExpression_0)
   在 ns64.Class592.vmethod_55(IExpression iexpression_0)
   在 ns25.Class595.ns0.Class658.method_30(IExpression iexpression_0, IType itype_2)
   在 ns25.Class595.ns0.Class658.vmethod_33(IAssignExpression iassignExpression_0)
   在 ns64.Class592.vmethod_55(IExpression iexpression_0)
   在 ns64.Class592.vmethod_34(IExpressionStatement iexpressionStatement_0)
   在 ns64.Class592.vmethod_26(IStatement istatement_0)
   在 ns64.Class592.method_10(IStatementCollection istatementCollection_0)
   在 ns64.Class592.vmethod_27(IBlockStatement iblockStatement_0)
   在 ns64.Class592.vmethod_26(IStatement istatement_0)
   在 ns64.Class592.vmethod_7(IMethodDeclaration imethodDeclaration_0)
   在 ns25.Class595.ns0.Class658.vmethod_7(IMethodDeclaration imethodDeclaration_0)
   在 ns25.Class595.vmethod_7(IMethodDeclaration imethodDeclaration_0)
   在 ns25.Class593.vmethod_7(IMethodDeclaration imethodDeclaration_0)
   在 ns64.Class592.vmethod_140(IMethodDeclarationCollection imethodDeclarationCollection_0)
   在 ns25.Class593.vmethod_5(ITypeDeclaration itypeDeclaration_0)
   在 ns3.Class594.TranslateTypeDeclaration(ITypeDeclaration itypeDeclaration_0, Boolean bool_0, Boolean bool_1)
   在 ns3.Class228.WriteTypeDeclaration(ITypeDeclaration itypeDeclaration_0, String string_3, ILanguageWriterConfiguration ilanguageWriterConfiguration_0)
namespace Kingdee.K3.FIN.BM.App.Core.PivotGrid
{
}

